/*
 * generated by Xtext
 */
package org.eclipsecon.expdsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ExpressionsRuntimeModule extends org.eclipsecon.expdsl.AbstractExpressionsRuntimeModule {

}
