sudo: false

language: java

jdk: oraclejdk7

cache:
  directories:
  - $HOME/.m2

env: DISPLAY=:99.0

install: true

before_script:
 - sh -e /etc/init.d/xvfb start
 
script:
 - export
 - mvn -f org.eclipsecon.expdsl.parent/pom.xml clean verify