/*
 * generated by Xtext
 */
package org.eclipsecon.expdsl.ui.contentassist

import org.eclipsecon.expdsl.ui.contentassist.AbstractExpressionsProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class ExpressionsProposalProvider extends AbstractExpressionsProposalProvider {
}
